import { ThemeName } from './types';

export interface Theme {
  id: ThemeName;
  name: string;
  category: 'dark' | 'light' | 'contrasting' | 'color';
  bg: string;
  accent: string;
}

export const THEMES: Theme[] = [
  { id: 'default', name: 'Default Dark', category: 'dark', bg: '#0a0a0c', accent: '#6366f1' },
  { id: 'cyberpunk', name: 'Cyberpunk Neon', category: 'contrasting', bg: '#05000a', accent: '#ff007f' },
  { id: 'Arcade', name: 'Arcade', category: 'contrasting', bg: '#050708', accent: '#db2777' },
  { id: 'wildfire', name: 'Wildfire Flame', category: 'color', bg: '#070301', accent: '#ea580c' },
  { id: 'synthwave', name: 'Synthwave Night', category: 'color', bg: '#04010a', accent: '#ff007f' },
  { id: 'electric-lime', name: 'Electric Lime', category: 'color', bg: '#020202', accent: '#a3e635' },
  { id: 'solar-storm', name: 'Solar Storm', category: 'color', bg: '#07050b', accent: '#f97316' },
  { id: 'magma', name: 'Magma Core', category: 'color', bg: '#050000', accent: '#ef4444' },
  { id: 'laser-tag', name: 'Laser Tag Arena', category: 'color', bg: '#050708', accent: '#db2777' },
  { id: 'acid', name: 'Acid', category: 'color', bg: '#020412', accent: '#eab308' },
  { id: 'jazz', name: 'Acid Jazz Gold', category: 'color', bg: '#020412', accent: '#eab308' },
  { id: 'crimson-void', name: 'Crimson Void', category: 'contrasting', bg: '#030000', accent: '#ff0000' },
  { id: 'toxic-waste', name: 'Toxic Chemical', category: 'contrasting', bg: '#010502', accent: '#ccff00' },
  { id: 'ocean-breeze', name: 'Ocean Breeze', category: 'color', bg: '#010c14', accent: '#3b82f6' },
  { id: 'forest-harmony', name: 'Forest Harmony', category: 'color', bg: '#020d09', accent: '#10b981' },
  { id: 'aurora-dream', name: 'Aurora Dream', category: 'color', bg: '#04020a', accent: '#a855f7' },
  { id: 'cozy-amber', name: 'Cozy Amber', category: 'dark', bg: '#0a0501', accent: '#d97706' },
  { id: 'lavender-haze', name: 'Lavender Haze', category: 'color', bg: '#07050d', accent: '#c084fc' },
  { id: 'slate-minimal', name: 'Slate Minimal', category: 'dark', bg: '#0b0f19', accent: '#475569' },
  { id: 'desert-dusk', name: 'Desert Dusk', category: 'dark', bg: '#0d0603', accent: '#f97316' },
  { id: 'rose-gold', name: 'Rose Gold Metallic', category: 'color', bg: '#0d040a', accent: '#be185d' },
  { id: 'mint-chocolate', name: 'Mint Cocoa', category: 'dark', bg: '#0c0806', accent: '#059669' },
  { id: 'glacier-hush', name: 'Glacier Cushioned', category: 'light', bg: '#f0f7ff', accent: '#38bdf8' },
  { id: 'candy-noir', name: 'Candy Noir Fizz', category: 'color', bg: '#050308', accent: '#ec4899' },
  { id: 'tropical', name: 'Tropical Island', category: 'color', bg: '#020b0a', accent: '#f97316' },
  { id: 'aurora', name: 'Aurora Borealis', category: 'color', bg: '#040814', accent: '#a855f7' },
  { id: 'solarpunk', name: 'Solarpunk Green', category: 'color', bg: '#060802', accent: '#eab308' },
  { id: 'vapor', name: 'Vaporwave Sunset', category: 'color', bg: '#0a0314', accent: '#38bdf8' },
  { id: 'ocean', name: 'Deep Sea Abyss', category: 'dark', bg: '#010510', accent: '#06b6d4' },
  { id: 'cyber-jade', name: 'Cyber Jade Slate', category: 'dark', bg: '#020606', accent: '#10b981' },
  { id: 'blossom', name: 'Cherry Blossom', category: 'light', bg: '#fff5f8', accent: '#db2777' },
  { id: 'infrared', name: 'Thermal Vector', category: 'contrasting', bg: '#070000', accent: '#ff2b00' },
  { id: 'psychedelic', name: 'Psychedelic Dream', category: 'color', bg: '#0a0110', accent: '#f43f5e' },
  { id: 'cyan-crimson', name: 'Cyan Crimson Edge', category: 'contrasting', bg: '#040810', accent: '#00ffff' },
  { id: 'sundial', name: 'Golden Sundial', category: 'light', bg: '#fffbf5', accent: '#2563eb' },
  { id: 'ethereal', name: 'Ethereal Fog', category: 'light', bg: '#fafafc', accent: '#a855f7' },
  { id: 'midnight-abyss', name: 'Midnight Abyss', category: 'dark', bg: '#020205', accent: '#7c3aed' },
  { id: 'coal-dust', name: 'Coal Dust Dark', category: 'dark', bg: '#0d0d0d', accent: '#525252' },
  { id: 'punk', name: 'Punk', category: 'contrasting', bg: '#05000a', accent: '#ff007f' },
  { id: 'wild', name: 'Wild', category: 'color', bg: '#070301', accent: '#ea580c' },
  { id: 'synth', name: 'Synth', category: 'color', bg: '#04010a', accent: '#ff007f' },
  { id: 'lime', name: 'Lime', category: 'color', bg: '#020202', accent: '#a3e635' },
  { id: 'pastel-dream', name: 'Pastel Dream', category: 'light', bg: '#0d0b14', accent: '#c084fc' },
  { id: 'sweet-peach', name: 'Sweet Peach', category: 'light', bg: '#120c0a', accent: '#fdba74' },
  { id: 'crimson-cerulean', name: 'Crimson & Cerulean', category: 'color', bg: '#050a12', accent: '#007acc' },
  { id: 'amber-blue', name: 'Amber Blue', category: 'color', bg: '#030815', accent: '#ff9800' },
  { id: 'amethyst-sun', name: 'Amethyst Sun', category: 'color', bg: '#0d021a', accent: '#c084fc' },
  { id: 'slate-violet', name: 'Slate & violet', category: 'dark', bg: '#11131A', accent: '#7F77DD' },
  { id: 'charcoal-amber', name: 'Charcoal & amber', category: 'dark', bg: '#13110E', accent: '#BA7517' },
  { id: 'ink-teal', name: 'Ink & teal', category: 'dark', bg: '#0E1413', accent: '#1D9E75' },
  { id: 'graphite-pink', name: 'Graphite & pink', category: 'dark', bg: '#121212', accent: '#D4537E' },
  { id: 'midnight-three-accents', name: 'Midnight & three accents', category: 'dark', bg: '#0D1218', accent: '#378ADD' },
  { id: 'obsidian-emerald', name: 'Obsidian & emerald', category: 'dark', bg: '#0D1410', accent: '#639922' },
  { id: 'espresso-coral', name: 'Espresso & coral', category: 'dark', bg: '#15110D', accent: '#D85A30' },
  { id: 'plum-gold', name: 'Plum & gold', category: 'dark', bg: '#150F1A', accent: '#BA7517' },
  { id: 'steel-crimson', name: 'Steel & crimson', category: 'dark', bg: '#10131A', accent: '#E24B4A' },
  { id: 'moss-rust', name: 'Moss & rust', category: 'dark', bg: '#11140E', accent: '#888780' },
  { id: 'indigo-lime', name: 'Indigo & lime', category: 'dark', bg: '#0E0F1A', accent: '#378ADD' },
  { id: 'carbon-rose', name: 'Carbon & rose', category: 'dark', bg: '#0E0E0E', accent: '#D4537E' },
  { id: 'forest-three-accents', name: 'Forest & three accents', category: 'dark', bg: '#0F1410', accent: '#639922' },
  { id: 'cobalt-three-accents', name: 'Cobalt & three accents', category: 'dark', bg: '#0D121A', accent: '#378ADD' },
  { id: 'maroon-four-accents', name: 'Maroon & four accents', category: 'dark', bg: '#150F0F', accent: '#D85A30' },
  { id: 'man-cave', name: 'Man cave', category: 'dark', bg: '#0a0a0c', accent: '#ff2e2e' },
  { id: 'slate-minimal-1', name: 'Slate minimal', category: 'dark', bg: '#0b0f19', accent: '#475569' },
  { id: 'coal-dust-1', name: 'Coal dust', category: 'dark', bg: '#0d0d0d', accent: '#525252' },
  { id: 'midnight-abyss-1', name: 'Midnight abyss', category: 'dark', bg: '#020205', accent: '#7c3aed' },
  { id: 'usa', name: 'USA', category: 'dark', bg: '#0a0e1a', accent: '#3b82f6' },
  { id: 'primary-colors', name: 'Primary colors', category: 'dark', bg: '#0d0d12', accent: '#3b82f6' },
  { id: 'sunset-blvd', name: 'Sunset blvd', category: 'dark', bg: '#241526', accent: '#ff7a5c' },
  { id: 'paper-violet', name: 'Paper & violet', category: 'light', bg: '#F7F6FB', accent: '#7F77DD' },
  { id: 'cream-amber', name: 'Cream & amber', category: 'light', bg: '#FBF7EF', accent: '#BA7517' },
  { id: 'mint-teal', name: 'Mint & teal', category: 'light', bg: '#F2FAF6', accent: '#0F6E56' },
  { id: 'blush-graphite', name: 'Blush & graphite', category: 'light', bg: '#FCF5F8', accent: '#993556' },
  { id: 'sky-coral', name: 'Sky & coral', category: 'light', bg: '#F2F8FD', accent: '#185FA5' },
  { id: 'linen-rust', name: 'Linen & rust', category: 'light', bg: '#FAF6F2', accent: '#993C1D' },
  { id: 'ivory-forest', name: 'Ivory & forest', category: 'light', bg: '#F8FAF1', accent: '#3B6D11' },
  { id: 'frost-indigo', name: 'Frost & indigo', category: 'light', bg: '#F4F5FA', accent: '#534AB7' },
  { id: 'sand-three-accents', name: 'Sand & three accents', category: 'light', bg: '#FCF8F0', accent: '#854F0B' },
  { id: 'cloud-three-accents', name: 'Cloud & three accents', category: 'light', bg: '#F5F6F8', accent: '#185FA5' },
  { id: 'glacier-hush-1', name: 'Glacier hush', category: 'light', bg: '#f0f7ff', accent: '#38bdf8' },
  { id: 'blossom-1', name: 'Blossom', category: 'light', bg: '#fff5f8', accent: '#db2777' },
  { id: 'sundial-1', name: 'Sundial', category: 'light', bg: '#fffbf5', accent: '#2563eb' },
  { id: 'ethereal-1', name: 'Ethereal', category: 'light', bg: '#fafafc', accent: '#a855f7' },
  { id: 'cyber-violet', name: 'Cyber violet', category: 'color', bg: '#08070D', accent: '#9B6BFF' },
  { id: 'acid-green', name: 'Acid green', category: 'color', bg: '#070A06', accent: '#9CFF3D' },
  { id: 'synthwave-sunset', name: 'Synthwave sunset', category: 'color', bg: '#0A0512', accent: '#FF3FA4' },
  { id: 'toxic-teal', name: 'Toxic teal', category: 'color', bg: '#050A09', accent: '#0FFFC1' },
  { id: 'laser-red', name: 'Laser red', category: 'color', bg: '#0A0606', accent: '#FF2D3D' },
  { id: 'plasma-blue', name: 'Plasma blue', category: 'color', bg: '#05080F', accent: '#2E9BFF' },
  { id: 'radioactive-amber', name: 'Radioactive amber', category: 'color', bg: '#0A0805', accent: '#FFB02E' },
  { id: 'vapor-magenta', name: 'Vapor magenta', category: 'color', bg: '#0A070A', accent: '#FF2EC4' },
  { id: 'grid-green-three-accents', name: 'Grid green & three accents', category: 'color', bg: '#060A06', accent: '#3DFF6B' },
  { id: 'outrun-purple-three-accents', name: 'Outrun purple & three accents', category: 'color', bg: '#08050D', accent: '#B14BFF' },
  { id: 'rainbow-grid', name: 'Rainbow grid', category: 'color', bg: '#070509', accent: '#9B6BFF' },
  { id: 'arcade-cabinet', name: 'Arcade cabinet', category: 'color', bg: '#0A0606', accent: '#FF2D3D' },
  { id: 'glow-stick-rave', name: 'Glow stick rave', category: 'color', bg: '#050A0A', accent: '#2EE6E6' },
  { id: 'tokyo-signage', name: 'Tokyo signage', category: 'color', bg: '#08070D', accent: '#FF2EC4' },
  { id: 'festival-mainstage', name: 'Festival mainstage', category: 'color', bg: '#0A0805', accent: '#FF7A1A' },
  { id: 'hazard-lime', name: 'Hazard lime', category: 'color', bg: '#070A06', accent: '#9CFF3D' },
  { id: 'outrun-dashboard', name: 'Outrun dashboard', category: 'color', bg: '#0A0512', accent: '#FF3FA4' },
  { id: 'terminal-overload', name: 'Terminal overload', category: 'color', bg: '#060A06', accent: '#3DFF6B' },
  { id: 'blacklight-party', name: 'Blacklight party', category: 'color', bg: '#05080F', accent: '#3D8BFF' },
  { id: 'carnival-chaos', name: 'Carnival chaos', category: 'color', bg: '#0A0805', accent: '#F5FF3D' },
  { id: 'cyberpunk-1', name: 'Cyberpunk', category: 'color', bg: '#0a0a0e', accent: '#fce300' },
  { id: 'cyan-crimson-1', name: 'Cyan crimson', category: 'color', bg: '#040810', accent: '#00ffff' },
  { id: 'crimson-void-1', name: 'Crimson void', category: 'color', bg: '#030000', accent: '#ff0000' },
  { id: 'infrared-1', name: 'Infrared', category: 'color', bg: '#070000', accent: '#ff2b00' },
  { id: 'deep-sea-neon', name: 'Deep sea neon', category: 'color', bg: '#070b16', accent: '#ff6b35' },
  { id: 'plasma-storm', name: 'Plasma storm', category: 'color', bg: '#0a0e18', accent: '#00b4ff' },
  { id: 'toxic-glow', name: 'Toxic glow', category: 'color', bg: '#080a08', accent: '#c6ff3a' },
  { id: 'neon-jungle', name: 'Neon jungle', category: 'color', bg: '#050e0d', accent: '#00ff8a' },
  { id: 'jellyfish', name: 'Jellyfish', category: 'color', bg: '#050b14', accent: '#ff5fd2' },
  { id: 'magma-frost', name: 'Magma frost', category: 'color', bg: '#090f16', accent: '#ff5733' },
  { id: 'galaxy-brain', name: 'Galaxy brain', category: 'color', bg: '#070613', accent: '#7b5cff' },
  { id: 'royal-wasp', name: 'Royal wasp', category: 'color', bg: '#120a1c', accent: '#f4d03f' },
  { id: 'cotton-candy-light', name: 'Cotton candy (light)', category: 'light', bg: '#FFF7FB', accent: '#FF9FCB' },
  { id: 'sherbet-light', name: 'Sherbet (light)', category: 'light', bg: '#FFFAF3', accent: '#FFC299' },
  { id: 'macaron-light', name: 'Macaron (light)', category: 'light', bg: '#FAF8FF', accent: '#C4B0FF' },
  { id: 'tropical-pastel-light', name: 'Tropical pastel (light)', category: 'light', bg: '#F7FFFC', accent: '#8FE8D9' },
  { id: 'spring-bloom-light', name: 'Spring bloom (light)', category: 'light', bg: '#FDFCF5', accent: '#AAB8FF' },
  { id: 'neon-pastel-violet-dark', name: 'Neon-pastel violet (dark)', category: 'light', bg: '#1C1330', accent: '#D9B8FF' },
  { id: 'dreamscape-teal-dark', name: 'Dreamscape teal (dark)', category: 'light', bg: '#10222B', accent: '#9DEEDC' },
  { id: 'cosmic-candy-dark', name: 'Cosmic candy (dark)', category: 'light', bg: '#160F22', accent: '#F5A8E0' },
  { id: 'soft-sunset-dark', name: 'Soft sunset (dark)', category: 'light', bg: '#221520', accent: '#FFC299' },
  { id: 'pastel-rainbow-three-accents-dark', name: 'Pastel rainbow & three accents (dark)', category: 'light', bg: '#191722', accent: '#A8DCFF' },
  { id: 'popsicle', name: 'Popsicle', category: 'light', bg: '#1a1622', accent: '#ff4d6d' },
  { id: 'lavender-haze-1', name: 'Lavender haze', category: 'light', bg: '#07050d', accent: '#c084fc' },
  { id: 'rosewater-slate', name: 'Rosewater slate', category: 'light', bg: '#15121a', accent: '#e8a0a0' },
  { id: 'rose-gold-1', name: 'Rose gold', category: 'light', bg: '#0d040a', accent: '#be185d' },
  { id: 'mint-chocolate-1', name: 'Mint chocolate', category: 'light', bg: '#0c0806', accent: '#059669' },
  { id: 'aurora-dream-1', name: 'Aurora dream', category: 'light', bg: '#04020a', accent: '#a855f7' },
  { id: 'aurora-1', name: 'Aurora', category: 'light', bg: '#040814', accent: '#a855f7' },
  { id: 'spectrum-slate', name: 'Spectrum slate', category: 'color', bg: '#11131A', accent: '#7F77DD' },
  { id: 'editorial-multi', name: 'Editorial multi', category: 'color', bg: '#FAF6F2', accent: '#993C1D' },
  { id: 'botanical-mix', name: 'Botanical mix', category: 'color', bg: '#F8FAF1', accent: '#3B6D11' },
  { id: 'carnival-print', name: 'Carnival print', category: 'color', bg: '#FBF7EF', accent: '#854F0B' },
  { id: 'midnight-kaleidoscope', name: 'Midnight kaleidoscope', category: 'color', bg: '#0D1218', accent: '#378ADD' },
  { id: 'sorbet-stack', name: 'Sorbet stack', category: 'color', bg: '#FCF5F8', accent: '#993556' },
  { id: 'workshop-palette', name: 'Workshop palette', category: 'color', bg: '#121212', accent: '#888780' },
  { id: 'harvest-table', name: 'Harvest table', category: 'color', bg: '#FCF8F0', accent: '#854F0B' },
  { id: 'deep-current', name: 'Deep current', category: 'color', bg: '#0E1413', accent: '#1D9E75' },
  { id: 'confetti-graphite', name: 'Confetti graphite', category: 'color', bg: '#0E0E0E', accent: '#D4537E' },
  { id: 'disco-ball', name: 'Disco ball', category: 'color', bg: '#13121c', accent: '#ff5fae' },
  { id: 'tropical-storm', name: 'Tropical storm', category: 'color', bg: '#140c1d', accent: '#ff9233' },
  { id: 'candy-pop', name: 'Candy pop', category: 'color', bg: '#171022', accent: '#ff5fa2' },
  { id: 'vaporwave', name: 'Vaporwave', category: 'color', bg: '#1b1330', accent: '#ff8fd6' },
  { id: 'plum', name: 'Plum', category: 'color', bg: '#160a14', accent: '#ff2d95' },
  { id: 'solar-flare', name: 'Solar flare', category: 'color', bg: '#0c0a1a', accent: '#ffc233' },
  { id: 'coral-reef', name: 'Coral reef', category: 'color', bg: '#071a1c', accent: '#ff7f6b' },
  { id: 'ocean-reef', name: 'Ocean reef', category: 'color', bg: '#081420', accent: '#27c2b8' },
  { id: 'psychedelic-1', name: 'Psychedelic', category: 'color', bg: '#0a0110', accent: '#f43f5e' },
  { id: 'tropical-1', name: 'Tropical', category: 'color', bg: '#020b0a', accent: '#f97316' },
  { id: 'forest', name: 'Forest', category: 'color', bg: '#0f1d17', accent: '#facc15' },
  { id: 'candy-noir-1', name: 'Candy noir', category: 'color', bg: '#050308', accent: '#ec4899' },
  { id: 'cyber-jade-1', name: 'Cyber jade', category: 'color', bg: '#020606', accent: '#10b981' },
  { id: 'ocean-1', name: 'Ocean', category: 'color', bg: '#010510', accent: '#06b6d4' },
  { id: 'ocean-breeze-1', name: 'Ocean breeze', category: 'color', bg: '#010c14', accent: '#3b82f6' },
  { id: 'forest-harmony-1', name: 'Forest harmony', category: 'color', bg: '#020d09', accent: '#10b981' },
  { id: 'primary-punch', name: 'Primary punch', category: 'contrasting', bg: '#0D0D0D', accent: '#E8362E' },
  { id: 'bauhaus-block', name: 'Bauhaus block', category: 'contrasting', bg: '#F5F3EC', accent: '#1755C4' },
  { id: 'pop-art-riot', name: 'Pop art riot', category: 'contrasting', bg: '#100D10', accent: '#E0188C' },
  { id: 'industrial-signal', name: 'Industrial signal', category: 'contrasting', bg: '#141210', accent: '#F2740C' },
  { id: 'comic-panel', name: 'Comic panel', category: 'contrasting', bg: '#FAFAF7', accent: '#F2C200' },
  { id: 'stadium-lights', name: 'Stadium lights', category: 'contrasting', bg: '#0D1410', accent: '#1FA34A' },
  { id: 'construction-zone', name: 'Construction zone', category: 'contrasting', bg: '#121212', accent: '#F2A000' },
  { id: 'royal-flush', name: 'Royal flush', category: 'contrasting', bg: '#0E0D1A', accent: '#7B2FD9' },
  { id: 'hard-candy', name: 'Hard candy', category: 'contrasting', bg: '#FCF8F5', accent: '#E0512C' },
  { id: 'maximum-saturation', name: 'Maximum saturation', category: 'contrasting', bg: '#0A0A0A', accent: '#0CB8C7' },
  { id: 'traffic-signal', name: 'Traffic signal', category: 'contrasting', bg: '#0B0F0B', accent: '#0FAE4A' },
  { id: 'voltage-white', name: 'Voltage white', category: 'contrasting', bg: '#FAFAFA', accent: '#0A5FE0' },
  { id: 'sirens', name: 'Sirens', category: 'contrasting', bg: '#0F0A0A', accent: '#EA1B1B' },
  { id: 'megaphone-yellow', name: 'Megaphone yellow', category: 'contrasting', bg: '#121006', accent: '#FFD500' },
  { id: 'ultraviolet-shock', name: 'Ultraviolet shock', category: 'contrasting', bg: '#0E0A14', accent: '#7A1FE0' },
  { id: 'concrete-jungle', name: 'Concrete jungle', category: 'contrasting', bg: '#161614', accent: '#FF6B00' },
  { id: 'liquid-mercury', name: 'Liquid mercury', category: 'contrasting', bg: '#080808', accent: '#00C2D6' },
  { id: 'fireworks-finale', name: 'Fireworks finale', category: 'contrasting', bg: '#0F080D', accent: '#E8009E' },
  { id: 'brick-chrome', name: 'Brick & chrome', category: 'contrasting', bg: '#140C0A', accent: '#D6281F' },
  { id: 'full-spectrum-overload', name: 'Full spectrum overload', category: 'contrasting', bg: '#0A0A0A', accent: '#EA1B1B' },
  { id: 'blood-orange', name: 'Blood orange', category: 'contrasting', bg: '#160c0a', accent: '#ff4d2e' },
  { id: 'magma-1', name: 'Magma', category: 'contrasting', bg: '#050000', accent: '#ef4444' },
  { id: 'laser-tag-1', name: 'Laser tag', category: 'contrasting', bg: '#050708', accent: '#db2777' },
  { id: 'desert-dusk-1', name: 'Desert dusk', category: 'contrasting', bg: '#0d0603', accent: '#f97316' },
  { id: 'pure-black-white', name: 'Pure black & white', category: 'contrasting', bg: '#000000', accent: '#FFFFFF' },
  { id: 'ink-on-paper', name: 'Ink on paper', category: 'contrasting', bg: '#FFFFFF', accent: '#000000' },
  { id: 'safety-yellow', name: 'Safety yellow', category: 'contrasting', bg: '#000000', accent: '#FFE600' },
  { id: 'stark-red-alert', name: 'Stark red alert', category: 'contrasting', bg: '#000000', accent: '#FF0000' },
  { id: 'electric-cyan-black', name: 'Electric cyan/black', category: 'contrasting', bg: '#000000', accent: '#00FFFF' },
  { id: 'maximum-aaa', name: 'Maximum AAA', category: 'contrasting', bg: '#FFFFFF', accent: '#0000FF' },
  { id: 'void-lime', name: 'Void & lime', category: 'contrasting', bg: '#000000', accent: '#39FF14' },
  { id: 'orange-hazard', name: 'Orange hazard', category: 'contrasting', bg: '#000000', accent: '#FF6A00' },
  { id: 'royal-blue-strike', name: 'Royal blue strike', category: 'contrasting', bg: '#000000', accent: '#1640FF' },
  { id: 'three-tone-hard-split', name: 'Three-tone hard split', category: 'contrasting', bg: '#000000', accent: '#FFFFFF' },
];
